### ISSUE TITLE
fumble is bloated because of it use of http-status as a dependency

### ISSUE THREAD

**Issue by carystanley** [yahoo/fumble#26]
fumble is bloated because of it use of http-status as a dependency

<img width="1229" alt="Screen Shot 2021-06-08 at 10 11 59 AM" src="https://user-images.githubusercontent.com/515507/121228760-fdb72600-c841-11eb-97cd-b13097dba4db.png">

You should consider removing http-status as a dependency

**Comment by redonkulus** [comment]
good find! @carystanley what should we use to replace it?

**Comment by carystanley** [comment]
Is the messaging aspect of fumble that important? The issue is the giant map in `http-status` that maps error code to string messages. It doesn't feel that useful to me.

**Comment by redonkulus** [comment]
It would definitely be a breaking change as I believe internally we may have test assertions on the descriptions as well.

**Comment by carystanley** [comment]
That sounds horrible that someone would assert the message 😞

**Comment by redonkulus** [comment]
looks like node.js supports this now too: https://nodejs.org/api/http.html#http_http_status_codes but that doesn't help for client side bundles

**Comment by carystanley** [comment]
If you want to remove it which I think is best, it would be a breaking change and require a major bump

**Comment by redonkulus** [comment]
fixed via https://github.com/yahoo/fumble/pull/27

**Comment by redonkulus** [comment]
fumble@0.1.7 published https://github.com/yahoo/fumble/releases/tag/v0.1.7
